# print("\tLinea 1\n" + "\tLinea 2 \n" + "\tlinea 3")
# print("\tA B C \n" + "\tD E F \n" + "\tG H I")
# input("digite su nombre:")
# input("digite su apellido: ")
#print("tu nombre es:" + input("digite su nombre: "))
# print("Estudio:"+ input ("¿Que esta estudiando?"))
# print("Vivo en : :"+ input ("¿En que pais vives:?"))
print("tu nombre  y apellido es:" + input("digite su nombre: ") + " " +  input("digite su apellido : ") )
