diccionario = {'c1':'valor1','c2':'valor2'}
print(type(diccionario))
resultado = diccionario['c1']
print(resultado)

# # cliente = {'nombre':'jhon','apellido':'rojas'}
# # consulta = cliente['ápellido']
# # print(consulta)

# dic = {'c1':155,'c2':[10,20,30],'c3':{'s1':100, 's2': 200}}
# print(dic['c2'][1])

# dic2 = {'c1':['a','b','c'],'c2':['d','e','f']}
# print(dic2['c2'][1].upper())

# dic3 = {1:'a',2:'b'}
# dic3[3] ='c'
# print(dic3)

