num1 = int(input("ingresa el numero: "))
# num2 = int (input("Ingresa el siguiente numero :"))
# print(f"{num1} dividido al piso {num2} es igual a {num1//num2}")
# print(f"{num1} modulo de {num2} es igual a {num1%num2}")
print(f"la raiz cuadrada de {num1} es igual a {num1**0.5}")
